# Generated by Django 5.2.17 on 2026-08-16 18:23

import core.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=24)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=128)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('medical_history_encrypted', core.encryption.EncryptedTextField(blank=True, default='')),
                ('current_medications_encrypted', core.encryption.EncryptedTextField(blank=True, default='')),
                ('allergies', models.CharField(blank=True, max_length=256)),
                ('notes_encrypted', core.encryption.EncryptedTextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
