# Generated by Django 5.2.17 on 2026-08-16 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title_en', models.CharField(max_length=256)),
                ('title_ar', models.CharField(max_length=256)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('DEPRESSION', 'Depression (الاكتئاب)'), ('ANXIETY', 'Anxiety (القلق)'), ('STRESS', 'Stress (التوتر والضغط النفسي)'), ('GENERAL', 'General Wellness (الصحة العامة)')], default='GENERAL', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('text_en', models.TextField()),
                ('text_ar', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessmentdefinition')),
            ],
            options={
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_value', models.IntegerField(default=0)),
                ('label_en', models.CharField(max_length=128)),
                ('label_ar', models.CharField(max_length=128)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.assessmentquestion')),
            ],
            options={
                'ordering': ['score_value'],
            },
        ),
        migrations.CreateModel(
            name='PatientAssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('severity_level', models.CharField(choices=[('MINIMAL', 'Minimal / None (طبيعي / طفيف)'), ('MILD', 'Mild (بسيط)'), ('MODERATE', 'Moderate (متوسط)'), ('MODERATELY_SEVERE', 'Moderately Severe (شديد نسبياً)'), ('SEVERE', 'Severe (شديد)')], default='MINIMAL', max_length=32)),
                ('interpretation_en', models.TextField(blank=True)),
                ('interpretation_ar', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assessmentdefinition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.patientassessmentsubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
