# Generated by Django 5.2.17 on 2026-08-16 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Dr.', help_text='e.g. Dr., Consultant, Specialist', max_length=64)),
                ('specialty', models.CharField(choices=[('CLINICAL_PSYCHOLOGY', 'Clinical Psychology (علاج نفسي إكلينيكي)'), ('PSYCHIATRY', 'Psychiatry (طب نفسي)'), ('CBT_SPECIALIST', 'Cognitive Behavioral Therapy - CBT (علاج سلوكي معرفي)'), ('CHILD_ADOLESCENT', 'Child & Adolescent Psychology (طب نفسي للأطفال والمراهقين)'), ('ANXIETY_MOOD', 'Anxiety & Mood Disorders (اضطرابات القلق والمزاج)'), ('TRAUMA_PTSD', 'Trauma & PTSD (الصدمات النفسية)'), ('FAMILY_COUNSELING', 'Family & Relationship Counseling (إرشاد أسري وزوجي)'), ('ADDICTION', 'Addiction Rehabilitation (علاج الإدمان)')], db_index=True, default='CLINICAL_PSYCHOLOGY', max_length=64)),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday (الاثنين)'), (1, 'Tuesday (الثلاثاء)'), (2, 'Wednesday (الأربعاء)'), (3, 'Thursday (الخميس)'), (4, 'Friday (الجمعة)'), (5, 'Saturday (السبت)'), (6, 'Sunday (الأحد)')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveIntegerField(default=45)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_title', models.CharField(max_length=256)),
                ('institution_name', models.CharField(max_length=256)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='doctor_qualifications/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='doctors.doctorprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
