from django.db import models
from django.conf import settings
from core.models import TimeStampedModel
from core.encryption import EncryptedTextField
from patients.models import PatientProfile
from doctors.models import DoctorProfile
from assessments.models import PatientAssessmentSubmission


class AIInterviewSession(TimeStampedModel):
    STATUS_CHOICES = (
        ('IN_PROGRESS', 'In Progress'),
        ('COMPLETED', 'Completed'),
        ('CANCELLED', 'Cancelled'),
    )

    STAGE_CHOICES = (
        ('GREETING', 'Initial Greeting & Consent'),
        ('MAIN_COMPLAINT', 'Main Complaint & Symptoms (الشكوى الأساسية والأعراض)'),
        ('SLEEP_ROUTINE', 'Sleep & Daily Functioning (النوم والروتين اليومي)'),
        ('MOOD_EMOTIONS', 'Mood & Emotional State (المزاج والحالة الشعورية)'),
        ('RISK_CHECK', 'Safety & Crisis Check (فحص السلامة والحالات الحرجة)'),
        ('SUMMARY_WRAPUP', 'Summary & Closing (التلخيص والختام)'),
    )

    patient = models.ForeignKey(
        PatientProfile,
        on_delete=models.CASCADE,
        related_name='ai_interview_sessions'
    )
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default='IN_PROGRESS', db_index=True)
    current_stage = models.CharField(max_length=32, choices=STAGE_CHOICES, default='GREETING')
    turn_count = models.PositiveIntegerField(default=0)
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"AI Interview - {self.patient.user.email} [{self.status}]"


class AIInterviewMessage(TimeStampedModel):
    SENDER_CHOICES = (
        ('AI', 'AI Assistant'),
        ('PATIENT', 'Patient'),
    )

    session = models.ForeignKey(
        AIInterviewSession,
        on_delete=models.CASCADE,
        related_name='messages'
    )
    sender = models.CharField(max_length=8, choices=SENDER_CHOICES)
    
    # Sensitive Patient Conversation Encrypted at Rest (AES-256)
    content_encrypted = EncryptedTextField()
    extracted_symptoms = models.JSONField(default=list, blank=True)
    sentiment_tag = models.CharField(max_length=32, blank=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f"[{self.session.id}] {self.sender}: {self.content_encrypted[:30]}..."


class AIReport(TimeStampedModel):
    RISK_CHOICES = (
        ('LOW', 'Low Risk (منخفض)'),
        ('MODERATE', 'Moderate Risk (متوسط)'),
        ('HIGH', 'High Risk / Immediate Attention (مرتفع / يتطلب متابعة عاجلة)'),
    )

    patient = models.ForeignKey(
        PatientProfile,
        on_delete=models.CASCADE,
        related_name='ai_reports'
    )
    interview_session = models.OneToOneField(
        AIInterviewSession,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='report'
    )
    assessment_submission = models.ForeignKey(
        PatientAssessmentSubmission,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='ai_reports'
    )

    # Encrypted Clinical Summaries (AraBART NLP Output)
    summary_ar_encrypted = EncryptedTextField(help_text="Arabic clinical summary generated by AraBART")
    summary_en_encrypted = EncryptedTextField(blank=True, default='')

    # Indicators & Clinical Decision Support (Decision Support only, BR-004 & BR-005)
    primary_indicators = models.JSONField(default=list, help_text="List of extracted condition indicators with confidence")
    preliminary_risk_level = models.CharField(max_length=16, choices=RISK_CHOICES, default='LOW', db_index=True)
    
    recommended_specialty = models.CharField(
        max_length=64,
        choices=DoctorProfile.SPECIALTY_CHOICES,
        default='CLINICAL_PSYCHOLOGY'
    )
    recommendation_reason_ar = models.TextField(blank=True)
    recommendation_reason_en = models.TextField(blank=True)
    
    # Safety notice & disclaimers (AI-016 & BR-004)
    safety_warning_triggered = models.BooleanField(default=False)
    disclaimer_notice = models.TextField(
        default="تنبيه: هذا التقرير هو تقييم أولي ودعم لاتخاذ القرار تم إنشاؤه بواسطة الذكاء الاصطناعي، ولا يمثل تشخيصاً طبياً نهائياً. التقييم والتشخيص النهائي يخضعان للطبيب المختص."
    )

    # Doctor Review Status (BR-003 & UC-006)
    is_reviewed_by_doctor = models.BooleanField(default=False, db_index=True)
    reviewed_by = models.ForeignKey(
        DoctorProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='reviewed_ai_reports'
    )
    doctor_review_notes_encrypted = EncryptedTextField(blank=True, default='')
    reviewed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"AI Report: {self.patient.user.get_full_name() or self.patient.user.email} [{self.preliminary_risk_level}]"
