# Generated by Django 5.2.17 on 2026-08-16 18:23

import core.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=16)),
                ('current_stage', models.CharField(choices=[('GREETING', 'Initial Greeting & Consent'), ('MAIN_COMPLAINT', 'Main Complaint & Symptoms (الشكوى الأساسية والأعراض)'), ('SLEEP_ROUTINE', 'Sleep & Daily Functioning (النوم والروتين اليومي)'), ('MOOD_EMOTIONS', 'Mood & Emotional State (المزاج والحالة الشعورية)'), ('RISK_CHECK', 'Safety & Crisis Check (فحص السلامة والحالات الحرجة)'), ('SUMMARY_WRAPUP', 'Summary & Closing (التلخيص والختام)')], default='GREETING', max_length=32)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interview_sessions', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInterviewMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('AI', 'AI Assistant'), ('PATIENT', 'Patient')], max_length=8)),
                ('content_encrypted', core.encryption.EncryptedTextField()),
                ('extracted_symptoms', models.JSONField(blank=True, default=list)),
                ('sentiment_tag', models.CharField(blank=True, max_length=32)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.aiinterviewsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_ar_encrypted', core.encryption.EncryptedTextField(help_text='Arabic clinical summary generated by AraBART')),
                ('summary_en_encrypted', core.encryption.EncryptedTextField(blank=True, default='')),
                ('primary_indicators', models.JSONField(default=list, help_text='List of extracted condition indicators with confidence')),
                ('preliminary_risk_level', models.CharField(choices=[('LOW', 'Low Risk (منخفض)'), ('MODERATE', 'Moderate Risk (متوسط)'), ('HIGH', 'High Risk / Immediate Attention (مرتفع / يتطلب متابعة عاجلة)')], db_index=True, default='LOW', max_length=16)),
                ('recommended_specialty', models.CharField(choices=[('CLINICAL_PSYCHOLOGY', 'Clinical Psychology (علاج نفسي إكلينيكي)'), ('PSYCHIATRY', 'Psychiatry (طب نفسي)'), ('CBT_SPECIALIST', 'Cognitive Behavioral Therapy - CBT (علاج سلوكي معرفي)'), ('CHILD_ADOLESCENT', 'Child & Adolescent Psychology (طب نفسي للأطفال والمراهقين)'), ('ANXIETY_MOOD', 'Anxiety & Mood Disorders (اضطرابات القلق والمزاج)'), ('TRAUMA_PTSD', 'Trauma & PTSD (الصدمات النفسية)'), ('FAMILY_COUNSELING', 'Family & Relationship Counseling (إرشاد أسري وزوجي)'), ('ADDICTION', 'Addiction Rehabilitation (علاج الإدمان)')], default='CLINICAL_PSYCHOLOGY', max_length=64)),
                ('recommendation_reason_ar', models.TextField(blank=True)),
                ('recommendation_reason_en', models.TextField(blank=True)),
                ('safety_warning_triggered', models.BooleanField(default=False)),
                ('disclaimer_notice', models.TextField(default='تنبيه: هذا التقرير هو تقييم أولي ودعم لاتخاذ القرار تم إنشاؤه بواسطة الذكاء الاصطناعي، ولا يمثل تشخيصاً طبياً نهائياً. التقييم والتشخيص النهائي يخضعان للطبيب المختص.')),
                ('is_reviewed_by_doctor', models.BooleanField(db_index=True, default=False)),
                ('doctor_review_notes_encrypted', core.encryption.EncryptedTextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports', to='assessments.patientassessmentsubmission')),
                ('interview_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='ai_engine.aiinterviewsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='patients.patientprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_reports', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
