# Generated by Django 5.2.17 on 2026-08-16 18:23

import core.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='خطة الرعاية والمتابعة النفسية', max_length=256)),
                ('diagnosis_summary_encrypted', core.encryption.EncryptedTextField(blank=True, default='')),
                ('clinical_notes_encrypted', core.encryption.EncryptedTextField(blank=True, default='')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (قيد التنفيذ)'), ('COMPLETED', 'Completed (مكتملة)'), ('PAUSED', 'Paused (موقوفة مؤقتاً)')], db_index=True, default='ACTIVE', max_length=16)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_treatment_plans', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='treatment.treatmentplan')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood_score', models.IntegerField(help_text='Mood score from 1 (Very Low) to 10 (Excellent)')),
                ('sleep_hours', models.DecimalField(decimal_places=1, default=7.0, max_digits=4)),
                ('anxiety_level', models.IntegerField(default=1, help_text='1 (None) to 5 (Severe)')),
                ('notes_encrypted', core.encryption.EncryptedTextField(blank=True, default='')),
                ('log_date', models.DateField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='patients.patientprofile')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='treatment.treatmentplan')),
            ],
            options={
                'ordering': ['-log_date', '-created_at'],
            },
        ),
    ]
