# Generated by Django 5.2.17 on 2026-09-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emergency_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='is_emergency',
            field=models.BooleanField(db_index=True, default=False, help_text='Emergency bypass flag used outside appointment window'),
        ),
    ]
