# Generated by Django 5.2.17 on 2026-09-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_emergency_reason_message_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='doctor_unlocked_until',
            field=models.DateTimeField(blank=True, help_text='Doctor manual chat unlock expiration time for the patient', null=True),
        ),
    ]
