# Generated by Django 5.2.17 on 2026-08-16 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('DOCTOR_VERIFY_APPROVED', 'Doctor Qualification Approved'), ('DOCTOR_VERIFY_REJECTED', 'Doctor Qualification Rejected'), ('ASSESSMENT_SUBMITTED', 'Assessment Submitted'), ('AI_INTERVIEW_COMPLETED', 'AI Interview Completed'), ('AI_REPORT_GENERATED', 'AI Preliminary Report Generated'), ('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('TREATMENT_PLAN_UPDATED', 'Treatment Plan Updated'), ('UNAUTHORIZED_ACCESS_ATTEMPT', 'Unauthorized Access Attempt')], db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
