# Generated by Django 5.2.17 on 2026-09-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('DOCTOR_VERIFY_APPROVED', 'Doctor Qualification Approved'), ('DOCTOR_VERIFY_REJECTED', 'Doctor Qualification Rejected'), ('ASSESSMENT_SUBMITTED', 'Assessment Submitted'), ('AI_INTERVIEW_COMPLETED', 'AI Interview Completed'), ('AI_REPORT_GENERATED', 'AI Preliminary Report Generated'), ('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('TREATMENT_PLAN_UPDATED', 'Treatment Plan Updated'), ('UNAUTHORIZED_ACCESS_ATTEMPT', 'Unauthorized Access Attempt'), ('CRISIS_SAFETY_PROTOCOL_ACTIVATED', 'Emergency Crisis Safety Protocol Activated')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_REQUESTED', 'New Appointment Request'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('SESSION_REMINDER', 'Session Reminder'), ('DOCTOR_APPLICATION_SUBMITTED', 'New Doctor Application'), ('DOCTOR_VERIFIED', 'Doctor License Approved'), ('DOCTOR_REJECTED', 'Doctor License Rejected'), ('SYSTEM_ALERT', 'System Alert'), ('CRISIS_ALERT', 'Urgent Patient Crisis / Suicide Alert')], db_index=True, max_length=64),
        ),
    ]
