# Generated by Django 5.2.17 on 2026-09-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_REQUESTED', 'New Appointment Request'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('SESSION_REMINDER', 'Session Reminder'), ('DOCTOR_APPLICATION_SUBMITTED', 'New Doctor Application'), ('DOCTOR_VERIFIED', 'Doctor License Approved'), ('DOCTOR_REJECTED', 'Doctor License Rejected'), ('SYSTEM_ALERT', 'System Alert'), ('CRISIS_ALERT', 'Urgent Patient Crisis / Suicide Alert'), ('NEW_MESSAGE', 'New Direct Message (رسالة محادثة جديدة)')], db_index=True, max_length=64),
        ),
    ]
